<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>管理员信息</title>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getStaticBasePath();?>/<?php echo $this->getStaticVersion();?>/manage/css/form.css">
<script type="text/javascript" src="<?php echo $this->getStaticBasePath();?>/<?php echo $this->getStaticVersion();?>/manage/js/jquery-1.6.4.min.js"></script>
</head>

<body>

<div class="form-container">
	<form action="" method="post">
        <input type="hidden" name="uid" value="83" />        
    	<p class="legend"><strong>注意:</strong>带*号的为必填字段.(<em>*</em>)</p>
    	<fieldset>
    		<legend>管理员信息</legend>
            <div>
                <label>用户名 <em>*</em></label>
                <input id="username" type="text" name="username" <?php if ($this->admin['username']){ echo "readonly='readonly'"; }?> value="<?php echo $this->admin['username'];?>"  />
            </div>
            
            <div>
                <label>密码 <em>*</em></label>
                <input id="password" type="password" name="password" value="" />
                修改时 为空则不修改，添加时 必须填写
            </div>
            
            <div>
                <label>正式姓名 <em>*</em></label>
                <input id="realname" type="text" name="admin_name" value="<?php echo $this->admin['admin_name'];?>" />
            </div>
            
            <div>
                <label>用户组 <em>*</em></label>
                <select id="deparment_id" name="department_id" style="width:150px;">
                <?php 
                foreach ($this->departments as $key => $value)
                {
                ?>
                    <option <?php if ($key == $this->admin['department_id']) { echo "selected"; } ?> value="<?php echo $key; ?>" ><?php echo $value; ?></option>
                <?php
                }
                ?>
                </select>
            </div>
    	</fieldset>
        <?php 
        if ($this->admin)
        {
        ?>
        <legend>管理组权限 <input name="privs_all" value="1" type="checkbox" id="privs_all" /> 所有权限</legend>            
            
            <?php 
            foreach ($this->menus as $top_menu)
            {
            ?>
                <fieldset style="border:1px solid #CCC;">
                <legend>
                    <?php echo $top_menu['menu_info']['menu_name'];?> &nbsp;
                    <input type="checkbox" class="top_menu" top_id="<?php echo $top_menu['menu_info']['menu_id'];?>" /> 全选
                </legend>
                <?php 
                    foreach ((array) $top_menu['sub_menus'] as $second_menu)
                    {
                ?>
                        <fieldset class="controlset" style="border:1px dotted #DDD;">
                        <legend class="label"><?php echo $second_menu['menu_info']['menu_name']; ?></legend>
                        <?php 
                        foreach ((array) $second_menu['sub_menus'] as $menu)
                        {
                        ?>
                            <input name="menu_ids[]" <?php if (isset($this->admin_auth_options[$menu['menu_id']])){ echo "checked='checked'";}?>  <?php if (isset($this->department_auth_options[$menu['menu_id']])){ echo "checked='checked' disabled='disabled'"; } else{ echo "class='top_menu_{$top_menu['menu_info']['menu_id']} menu'"; }?>  value="<?php echo $menu['menu_id'];?>" type="checkbox" /><span><?php echo $menu['menu_name'];?></span>
                        <?php 
                        }
                        ?>
                         </fieldset>
                <?php 
                    }
                ?>   
                </fieldset>
        <?php 
            }
        }
        ?>

    	<div class="buttonrow">
    		<input type="submit" value="提交" class="button" />&nbsp;&nbsp;
            <input type="button" value="取消" class="button" onclick="history.go(-1);" />
    	</div>
	</form>
</div>
<script type="text/javascript">
jQuery(document).ready(function(){
    jQuery('#privs_all').click(function(){
        jQuery('.menu').attr('checked', this.checked);
    });
    
    jQuery('.top_menu').click(function(){
        var top_id = jQuery(this).attr('top_id');
        jQuery('.top_menu_' + top_id).attr('checked', this.checked);
    });
});
</script>
</body>
</html>
 