<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title></title>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getStaticBasePath();?>/<?php echo $this->getStaticVersion();?>/manage/css/ui/jquery.ui.all.css">
<link rel="stylesheet" type="text/css" href="<?php echo $this->getStaticBasePath();?>/<?php echo $this->getStaticVersion();?>/manage/css/data.css">
<script type="text/javascript" src="<?php echo $this->getStaticBasePath();?>/<?php echo $this->getStaticVersion();?>/manage/js/jquery-1.6.4.min.js"></script>
<script type="text/javascript" src="<?php echo $this->getStaticBasePath();?>/<?php echo $this->getStaticVersion();?>/manage/js/jquery-ui-1.8.16.custom.min.js"></script>
<script type="text/javascript" src="<?php echo $this->getStaticBasePath();?>/<?php echo $this->getStaticVersion();?>/manage/js/jquery.ui.datepicker-zh-CN.js"></script>
<style type="text/css">
.p5{padding:5px;}
.p10{padding:10px;}

td { line-height: 30px; }
td a { text-decoration: none; color: #0000ee; }
td span.left { float: left; padding-left: 5px; }
td span.right { float: right; padding-right: 5px; }
td span.right a { color: #000; }
.link_03 a{text-decoration:none;}
.link_03{overflow:hidden;margin-bottom:6px;}
.link_03 ul{padding:0px; margin:0px;}
.link_03 li{float:left; list-style:none; margin-right:6px; padding:0px 6px; line-height:18px; border:1px solid #A1A1A1}
.link_03 li.cur{ background:#ddd}
.link_03 li.cur a{color:#ff33ff;}
.link_02 span {min-width: 28px;padding-left: 0px;display: inline-block;margin-left: 0px;}

/*list select*/
.optionSel{width:100%;margin:0px auto;margin-bottom:10px;background:#b5d6e6;}
.optionSel td{padding:5px;}
.optionSel select{border:1px solid #999;padding:3px;}
.optionSel .input{border:1px solid #999;padding:3px;}
</style>
</head><body>
<!--Table header {-->
<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td width="12"><img width="12" height="30" src="<?php echo $this->getStaticBasePath();?>/<?php echo $this->getStaticVersion();?>/manage/images/tab_03.gif"></td>
    <td align="left" valign="middle" background="<?php echo $this->getStaticBasePath();?>/<?php echo $this->getStaticVersion();?>/manage/images/tab_05.gif">
    
    <!--table header content {-->
    <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
      <tr>
        <td width="50%" align="left"><img src="<?php echo $this->getStaticBasePath();?>/<?php echo $this->getStaticVersion();?>/manage/images/tb.gif" width="16" height="16" border="0" align="absmiddle" /> 当前位置：<a href="/system/menumanage">菜单列表</a></td>
        <td width="50%" align="right"><a href="/system/addmenu">添加菜单</a></td>
      </tr>
    </table>
    <!--} table header content-->
    
    </td>
    <td width="16"><img width="16" height="30" src="<?php echo $this->getStaticBasePath();?>/<?php echo $this->getStaticVersion();?>/manage/images/tab_07.gif"></td>
  </tr>
</table>
<!--} Table header-->

<!--Table content {-->
<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td width="8" background="<?php echo $this->getStaticBasePath();?>/<?php echo $this->getStaticVersion();?>/manage/images/tab_12.gif"></td>
    <td style="padding:10px;">
        <!--content {-->
<table width="100%" border="0" cellpadding="5" cellspacing="1" bgcolor="b5d6e6">
          <tr align="center" bgcolor="#CDE9FC">
            <th style="display:none;" width="10%"><input type="checkbox" name="selectAll" value="1" class="selectAll" for="id[]" title="全选" /></th>
            <th width="10%">编号</th>
            <th width="10%">菜单级别</th>
            <th width="10%">
            <select name="sys" id="sys" onchange="document.location.href='/system/menumanage?top_id=' + this.value;">
            <option value="">全部系统</option>
                <?php 
                foreach ($this->top_menus as $key => $value)
                {
                ?>
                        <option <?php if ($key == $_GET['top_id']){ echo "selected='selected'";}?> value="<?php echo $key;?>" ><?php echo $value;?></option>
                <?php 
                }
                ?>

            </select>
            </th>
            <th width="10%">菜单名称</th>
            <th width="10%">菜单链接</th>
            <th width="10%">显示菜单</th>
            <th width="10%">排序</th>
            <th width="20%">基本操作</th>
          </tr>
          <?php 
          foreach ($this->menu_list as $menu)
          {
          ?>
          <tr align="center" valign="middle" bgcolor="#FFFFFF" onMouseOver="this.bgColor='#eeeeee'" onMouseOut="this.bgColor='#FFFFFF'">
            <td style="display:none;"><input type="checkbox" name="id[]" value="<?php echo $menu['menu_id'];?>" /></td>
            <td><?php echo $menu['menu_id'];?></td>
            <td><?php echo $menu['menu_level'];?>级菜单</td>
            <td><?php echo $menu['first_menu_name'];?></td>
            <td><?php echo $menu['menu_name'];?></td>
            <td><?php if ($menu['menu_level'] == 3){ echo "/{$menu['controller']}/{$menu['action']}";}?></td>
            <td><?php echo $menu['is_show'] == 1 ? '显示' : '不显示'; ?></td>
            <td><?php echo $menu['sort'];?></td>
            <td>
                <img src="<?php echo $this->getStaticBasePath();?>/<?php echo $this->getStaticVersion();?>/manage/images/edt.gif" width="16" height="16" />
                <a href="/system/editmenu?menu_id=<?php echo $menu['menu_id'];?>">编辑</a>&nbsp; &nbsp;
                <img src="<?php echo $this->getStaticBasePath();?>/<?php echo $this->getStaticVersion();?>/manage/images/del.gif" width="16" height="16" />
                <a href="/system/deletemenu?menu_id=<?php echo $menu['menu_id'];?>" onclick="return confirm('确认要删除吗？');">删除</a>
            </td>
          </tr>
          <?php 
          }
          ?>
          </table>        
        <!--} content-->              
    </td>
    <td width="8" background="<?php echo $this->getStaticBasePath();?>/<?php echo $this->getStaticVersion();?>/manage/images/tab_15.gif"></td>
  </tr>
</table>
<!--} Table content-->

<!--Table footer {-->
<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td width="12"><img width="12" height="35" src="<?php echo $this->getStaticBasePath();?>/<?php echo $this->getStaticVersion();?>/manage/images/tab_18.gif"></td>
    <td align="left" valign="middle" background="<?php echo $this->getStaticBasePath();?>/<?php echo $this->getStaticVersion();?>/manage/images/tab_19.gif">    
        <!--content {--><div id="page" class="link_03">
                <?php echo $this->page;?>
            </div>
        <!--} content-->
    </td>
    <td width="16"><img width="16" height="35" src="<?php echo $this->getStaticBasePath();?>/<?php echo $this->getStaticVersion();?>/manage/images/tab_20.gif"></td>
  </tr>
</table>
<!--} Table footer-->

</body>
</html>
