<!--Begin Datatables-->
<div class="row">
  <div class="col-lg-12">
    <div class="box">
      <header>
        <div class="icons">
          <i class="fa fa-table"></i>
        </div>
        <h5>Dynamic Table</h5>
      </header>
      <div id="collapse4" class="body">
        <table id="dataTable" class="table table-bordered table-condensed table-hover table-striped">
          <thead>
            <tr>
              <th>Rendering engine</th>
              <th>Browser</th>
              <th>Platform(s)</th>
              <th>Engine version</th>
              <th>CSS grade</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Trident</td>
              <td>Internet Explorer 4.0</td>
              <td>Win 95+</td>
              <td>4</td>
              <td>X</td>
            </tr>
            <tr>
              <td>Trident</td>
              <td>Internet Explorer 5.0</td>
              <td>Win 95+</td>
              <td>5</td>
              <td>C</td>
            </tr>
            <tr>
              <td>Trident</td>
              <td>Internet Explorer 5.5</td>
              <td>Win 95+</td>
              <td>5.5</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Trident</td>
              <td>Internet Explorer 6</td>
              <td>Win 98+</td>
              <td>6</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Trident</td>
              <td>Internet Explorer 7</td>
              <td>Win XP SP2+</td>
              <td>7</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Trident</td>
              <td>AOL browser (AOL desktop)</td>
              <td>Win XP</td>
              <td>6</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Gecko</td>
              <td>Firefox 1.0</td>
              <td>Win 98+ / OSX.2+</td>
              <td>1.7</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Gecko</td>
              <td>Firefox 1.5</td>
              <td>Win 98+ / OSX.2+</td>
              <td>1.8</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Gecko</td>
              <td>Firefox 2.0</td>
              <td>Win 98+ / OSX.2+</td>
              <td>1.8</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Gecko</td>
              <td>Firefox 3.0</td>
              <td>Win 2k+ / OSX.3+</td>
              <td>1.9</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Gecko</td>
              <td>Camino 1.0</td>
              <td>OSX.2+</td>
              <td>1.8</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Gecko</td>
              <td>Camino 1.5</td>
              <td>OSX.3+</td>
              <td>1.8</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Gecko</td>
              <td>Netscape 7.2</td>
              <td>Win 95+ / Mac OS 8.6-9.2</td>
              <td>1.7</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Gecko</td>
              <td>Netscape Browser 8</td>
              <td>Win 98SE+</td>
              <td>1.7</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Gecko</td>
              <td>Netscape Navigator 9</td>
              <td>Win 98+ / OSX.2+</td>
              <td>1.8</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Gecko</td>
              <td>Mozilla 1.0</td>
              <td>Win 95+ / OSX.1+</td>
              <td>1</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Gecko</td>
              <td>Mozilla 1.1</td>
              <td>Win 95+ / OSX.1+</td>
              <td>1.1</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Gecko</td>
              <td>Mozilla 1.2</td>
              <td>Win 95+ / OSX.1+</td>
              <td>1.2</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Gecko</td>
              <td>Mozilla 1.3</td>
              <td>Win 95+ / OSX.1+</td>
              <td>1.3</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Gecko</td>
              <td>Mozilla 1.4</td>
              <td>Win 95+ / OSX.1+</td>
              <td>1.4</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Gecko</td>
              <td>Mozilla 1.5</td>
              <td>Win 95+ / OSX.1+</td>
              <td>1.5</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Gecko</td>
              <td>Mozilla 1.6</td>
              <td>Win 95+ / OSX.1+</td>
              <td>1.6</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Gecko</td>
              <td>Mozilla 1.7</td>
              <td>Win 98+ / OSX.1+</td>
              <td>1.7</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Gecko</td>
              <td>Mozilla 1.8</td>
              <td>Win 98+ / OSX.1+</td>
              <td>1.8</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Gecko</td>
              <td>Seamonkey 1.1</td>
              <td>Win 98+ / OSX.2+</td>
              <td>1.8</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Gecko</td>
              <td>Epiphany 2.20</td>
              <td>Gnome</td>
              <td>1.8</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Webkit</td>
              <td>Safari 1.2</td>
              <td>OSX.3</td>
              <td>125.5</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Webkit</td>
              <td>Safari 1.3</td>
              <td>OSX.3</td>
              <td>312.8</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Webkit</td>
              <td>Safari 2.0</td>
              <td>OSX.4+</td>
              <td>419.3</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Webkit</td>
              <td>Safari 3.0</td>
              <td>OSX.4+</td>
              <td>522.1</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Webkit</td>
              <td>OmniWeb 5.5</td>
              <td>OSX.4+</td>
              <td>420</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Webkit</td>
              <td>iPod Touch / iPhone</td>
              <td>iPod</td>
              <td>420.1</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Webkit</td>
              <td>S60</td>
              <td>S60</td>
              <td>413</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Presto</td>
              <td>Opera 7.0</td>
              <td>Win 95+ / OSX.1+</td>
              <td>-</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Presto</td>
              <td>Opera 7.5</td>
              <td>Win 95+ / OSX.2+</td>
              <td>-</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Presto</td>
              <td>Opera 8.0</td>
              <td>Win 95+ / OSX.2+</td>
              <td>-</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Presto</td>
              <td>Opera 8.5</td>
              <td>Win 95+ / OSX.2+</td>
              <td>-</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Presto</td>
              <td>Opera 9.0</td>
              <td>Win 95+ / OSX.3+</td>
              <td>-</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Presto</td>
              <td>Opera 9.2</td>
              <td>Win 88+ / OSX.3+</td>
              <td>-</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Presto</td>
              <td>Opera 9.5</td>
              <td>Win 88+ / OSX.3+</td>
              <td>-</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Presto</td>
              <td>Opera for Wii</td>
              <td>Wii</td>
              <td>-</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Presto</td>
              <td>Nokia N800</td>
              <td>N800</td>
              <td>-</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Presto</td>
              <td>Nintendo DS browser</td>
              <td>Nintendo DS</td>
              <td>8.5</td>
              <td>C/A1</td>
            </tr>
            <tr>
              <td>KHTML</td>
              <td>Konqureror 3.1</td>
              <td>KDE 3.1</td>
              <td>3.1</td>
              <td>C</td>
            </tr>
            <tr>
              <td>KHTML</td>
              <td>Konqureror 3.3</td>
              <td>KDE 3.3</td>
              <td>3.3</td>
              <td>A</td>
            </tr>
            <tr>
              <td>KHTML</td>
              <td>Konqureror 3.5</td>
              <td>KDE 3.5</td>
              <td>3.5</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Tasman</td>
              <td>Internet Explorer 4.5</td>
              <td>Mac OS 8-9</td>
              <td>-</td>
              <td>X</td>
            </tr>
            <tr>
              <td>Tasman</td>
              <td>Internet Explorer 5.1</td>
              <td>Mac OS 7.6-9</td>
              <td>1</td>
              <td>C</td>
            </tr>
            <tr>
              <td>Tasman</td>
              <td>Internet Explorer 5.2</td>
              <td>Mac OS 8-X</td>
              <td>1</td>
              <td>C</td>
            </tr>
            <tr>
              <td>Misc</td>
              <td>NetFront 3.1</td>
              <td>Embedded devices</td>
              <td>-</td>
              <td>C</td>
            </tr>
            <tr>
              <td>Misc</td>
              <td>NetFront 3.4</td>
              <td>Embedded devices</td>
              <td>-</td>
              <td>A</td>
            </tr>
            <tr>
              <td>Misc</td>
              <td>Dillo 0.8</td>
              <td>Embedded devices</td>
              <td>-</td>
              <td>X</td>
            </tr>
            <tr>
              <td>Misc</td>
              <td>Links</td>
              <td>Text only</td>
              <td>-</td>
              <td>X</td>
            </tr>
            <tr>
              <td>Misc</td>
              <td>Lynx</td>
              <td>Text only</td>
              <td>-</td>
              <td>X</td>
            </tr>
            <tr>
              <td>Misc</td>
              <td>IE Mobile</td>
              <td>Windows Mobile 6</td>
              <td>-</td>
              <td>C</td>
            </tr>
            <tr>
              <td>Misc</td>
              <td>PSP browser</td>
              <td>PSP</td>
              <td>-</td>
              <td>C</td>
            </tr>
            <tr>
              <td>Other browsers</td>
              <td>All others</td>
              <td>-</td>
              <td>-</td>
              <td>U</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div><!-- /.row -->

<!--End Datatables-->
<div class="row">

  <!-- .col-lg-6 -->
  <div class="col-lg-6">
    <div class="box">
      <header>
        <h5>Default styles</h5>
        <div class="toolbar">
          <div class="btn-group">
            <a href="#defaultTable" data-toggle="collapse" class="btn btn-sm btn-default minimize-box">
              <i class="fa fa-angle-up"></i>
            </a> 
            <a class="btn btn-danger btn-sm close-box">
              <i class="fa fa-times"></i>
            </a> 
          </div>
        </div>
      </header>
      <div id="defaultTable" class="body collapse in">
        <table class="table responsive-table">
          <thead>
            <tr>
              <th>#</th>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Score</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td>Jill</td>
              <td>Smith</td>
              <td>50</td>
            </tr>
            <tr>
              <td>2</td>
              <td>Eve</td>
              <td>Jackson</td>
              <td>94</td>
            </tr>
            <tr>
              <td>3</td>
              <td>John</td>
              <td>Doe</td>
              <td>80</td>
            </tr>
            <tr>
              <td>4</td>
              <td>Adam</td>
              <td>Johnson</td>
              <td>67</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div><!-- /.col-lg-6 -->

  <!-- .col-lg-6 -->
  <div class="col-lg-6">
    <div class="box">
      <header>
        <h5>Table Striped</h5>
        <div class="toolbar">
          <div class="btn-group">
            <a href="#stripedTable" data-toggle="collapse" class="btn btn-default btn-sm minimize-box">
              <i class="fa fa-angle-up"></i>
            </a> 
            <a class="btn btn-danger btn-sm close-box">
              <i class="fa fa-times"></i>
            </a> 
          </div>
        </div>
      </header>
      <div id="stripedTable" class="body collapse in">
        <table class="table table-striped responsive-table">
          <thead>
            <tr>
              <th>#</th>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Score</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td>Jill</td>
              <td>Smith</td>
              <td>50</td>
            </tr>
            <tr>
              <td>2</td>
              <td>Eve</td>
              <td>Jackson</td>
              <td>94</td>
            </tr>
            <tr>
              <td>3</td>
              <td>John</td>
              <td>Doe</td>
              <td>80</td>
            </tr>
            <tr>
              <td>4</td>
              <td>Adam</td>
              <td>Johnson</td>
              <td>67</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div><!-- /.col-lg-6 -->
</div>
<div class="row">

  <!-- .col-lg-6 -->
  <div class="col-lg-6">
    <div class="box">
      <header>
        <h5>Table Bordered</h5>
        <div class="toolbar">
          <div class="btn-group">
            <a href="#borderedTable" data-toggle="collapse" class="btn btn-default btn-sm minimize-box">
              <i class="fa fa-angle-up"></i>
            </a> 
            <a class="btn btn-danger btn-sm close-box">
              <i class="fa fa-times"></i>
            </a> 
          </div>
        </div>
      </header>
      <div id="borderedTable" class="body collapse in">
        <table class="table table-bordered responsive-table">
          <thead>
            <tr>
              <th>#</th>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Score</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td>Jill</td>
              <td>Smith</td>
              <td>50</td>
            </tr>
            <tr>
              <td>2</td>
              <td>Eve</td>
              <td>Jackson</td>
              <td>94</td>
            </tr>
            <tr>
              <td>3</td>
              <td>John</td>
              <td>Doe</td>
              <td>80</td>
            </tr>
            <tr>
              <td>4</td>
              <td>Adam</td>
              <td>Johnson</td>
              <td>67</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div><!-- /.col-lg-6 -->

  <!-- .col-lg-6 -->
  <div class="col-lg-6">
    <div class="box">
      <header>
        <h5>Table Condensed</h5>
        <div class="toolbar">
          <div class="btn-group">
            <a href="#condensedTable" data-toggle="collapse" class="btn btn-default btn-sm minimize-box">
              <i class="fa fa-angle-up"></i>
            </a> 
            <a class="btn btn-danger btn-sm close-box">
              <i class="fa fa-times"></i>
            </a> 
          </div>
        </div>
      </header>
      <div id="condensedTable" class="body collapse in">
        <table class="table table-condensed responsive-table">
          <thead>
            <tr>
              <th>#</th>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Score</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td>Jill</td>
              <td>Smith</td>
              <td>50</td>
            </tr>
            <tr>
              <td>2</td>
              <td>Eve</td>
              <td>Jackson</td>
              <td>94</td>
            </tr>
            <tr>
              <td>3</td>
              <td>John</td>
              <td>Doe</td>
              <td>80</td>
            </tr>
            <tr>
              <td>4</td>
              <td>Adam</td>
              <td>Johnson</td>
              <td>67</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div><!-- /.col-lg-6 -->
</div>
<div class="row">

  <!-- .col-lg-6 -->
  <div class="col-lg-6">
    <div class="box">
      <header>
        <h5>Optional row classes</h5>
        <div class="toolbar">
          <div class="btn-group">
            <a href="#optionalTable" data-toggle="collapse" class="btn btn-default btn-sm minimize-box">
              <i class="fa fa-angle-up"></i>
            </a> 
            <a class="btn btn-danger btn-sm close-box">
              <i class="fa fa-times"></i>
            </a> 
          </div>
        </div>
      </header>
      <div id="optionalTable" class="body collapse in">
        <table class="table responsive-table">
          <thead>
            <tr>
              <th>#</th>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Score</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td>Jill</td>
              <td>Smith</td>
              <td>50</td>
            </tr>
            <tr>
              <td>2</td>
              <td>Eve</td>
              <td>Jackson</td>
              <td>94</td>
            </tr>
            <tr>
              <td>3</td>
              <td>John</td>
              <td>Doe</td>
              <td>80</td>
            </tr>
            <tr>
              <td>4</td>
              <td>Adam</td>
              <td>Johnson</td>
              <td>67</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div><!-- /.col-lg-6 -->

  <!-- .col-lg-6 -->
  <div class="col-lg-6">
    <div class="box">
      <header>
        <h5>Sortable Table</h5>
        <div class="toolbar">
          <div class="btn-group">
            <a href="#sortableTable" data-toggle="collapse" class="btn btn-default btn-sm minimize-box">
              <i class="fa fa-angle-up"></i>
            </a> 
            <a class="btn btn-danger btn-sm close-box">
              <i class="fa fa-times"></i>
            </a> 
          </div>
        </div>
      </header>
      <div id="sortableTable" class="body collapse in">
        <table class="table table-bordered sortableTable responsive-table">
          <thead>
            <tr>
              <th>#
                <i class="fa sort"></i>
              </th>
              <th>First Name
                <i class="fa sort"></i>
              </th>
              <th>Last Name
                <i class="fa sort"></i>
              </th>
              <th>Score
                <i class="fa sort"></i>
              </th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td>Jill</td>
              <td>Smith</td>
              <td>50</td>
            </tr>
            <tr>
              <td>2</td>
              <td>Eve</td>
              <td>Jackson</td>
              <td>94</td>
            </tr>
            <tr>
              <td>3</td>
              <td>John</td>
              <td>Doe</td>
              <td>80</td>
            </tr>
            <tr>
              <td>4</td>
              <td>Adam</td>
              <td>Johnson</td>
              <td>67</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div><!-- /.col-lg-6 -->
</div>