<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>无标题文档</title>
<style type="text/css">
<!--
body { margin: 0px; overflow: hidden; }
.menu_title span {
	font-weight: bold; left: 3px; color: #ffffff; position: relative; top: 2px;
}
.menu_title2 span {
	font-weight: bold; left: 3px; color: #ffcc00; position: relative; top: 2px;
}
.version { font-size: 12px; color: #033d61; }

ul, li { margin: 0px; padding: 0px; list-style-type: none; }

#sub_menu_bar { width:151px; margin: 0 7px; }

.menu_title {
    width:151px; font-size:13px; color:#fff; height:23px; line-height:23px;
    margin-top:5px; text-align:center; cursor:pointer;
    background:url('<?php echo $this->getStaticBasePath();?>/<?php echo $this->getStaticVersion();?>/manage/images/main_47.gif');
}
.menu_list { width:149px; min-height:50px; padding-bottom:6px; border: 1px solid #7bc4d3; *width:151px; }
.menu_list li {
    width:120px; height:15px; padding: 0px 0 0px 15px;
    margin: 6px 8px 0 8px; cursor:hand; font-size: 12px; color: #033D61;
    background:url('<?php echo $this->getStaticBasePath();?>/<?php echo $this->getStaticVersion();?>/manage/images/left.gif') no-repeat;
}
.menu_list li a { text-decoration:none; color: #033D61; display:block; }
.menu_list li:hover, 
.menu_list li.hover { width:125px; background-color: #7bc4d3; }

#switchPoint { width: 6px; height: 40px; display: block; color: white; cursor: hand; font-family: webdings; font-size: 9pt; }
.switch_01 { background:url('<?php echo $this->getStaticBasePath();?>/<?php echo $this->getStaticVersion();?>/manage/images/main_55.gif'); }
.switch_02 { background:url('<?php echo $this->getStaticBasePath();?>/<?php echo $this->getStaticVersion();?>/manage/images/main_55_1.gif'); }

#manage_title { font-size: 12px; color: #FFFFFF; background:url('<?php echo $this->getStaticBasePath();?>/<?php echo $this->getStaticVersion();?>/manage/images/main_40.gif'); }
-->
</style>
<script type="text/javascript" src="<?php echo $this->getStaticBasePath();?>/<?php echo $this->getStaticVersion();?>/manage/js/jquery-1.6.4.min.js"></script>
</head>

<body style="overflow:hidden">
<table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0" style="table-layout:fixed;">
  <tr>
    <td>
    <table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0" style="table-layout:fixed;">
      <tr>
        <td width="171" id=frmTitle noWrap name="fmTitle" align="center" valign="top">
        <table width="171" height="100%" border="0" cellpadding="0" cellspacing="0" style="table-layout:fixed;">
          <tr>
            <td  bgcolor="#1873aa" style="width:6px;">&nbsp;</td>
            <td width="165">
                <table width="165" height="100%" border="0" cellpadding="0" cellspacing="0">
                  <tr>
                    <td height="28" align="center" id="manage_title">管理菜单</td>
                  </tr>
                  <tr>
                    <td valign="top">
                        <div id="sub_menu_bar">                            
                        </div>
                      </td>
                  </tr>
                  <tr>
                    <td height="18" background="<?php echo $this->getStaticBasePath();?>/<?php echo $this->getStaticVersion();?>/manage/images/main_58.gif">
                        <div align="center" class="version">版本：V1.1 (20120116)</div>
                    </td>
                  </tr>
                </table>
            </td>
          </tr>
        </table>
    </td>
    
    <td width="6"  style="width:6px;"valign="middle" bgcolor="1873aa">
    	<span id="switchPoint" title="关闭/打开左栏" class="switch_01"></span>
	</td>
    
    <td width="100%" align="center" valign="top">
    	<iframe src="/admin/welcome" id="subFrame" name="subFrame" height="100%" width="100%" border="0" frameborder="0"></iframe>
    </td>

    <td width="6" bgcolor="#1873aa" style=" width:6px;">&nbsp;</td>
  </tr>
</table>

<script type="text/javascript">
function switchSysBar() {
    $('#switchPoint').click();
}

$('#switchPoint').click(function() {
    $('#frmTitle').toggle();
}).toggle(
    function(){ $(this).removeClass('switch_01').addClass('switch_02'); },
    function(){ $(this).removeClass('switch_02').addClass('switch_01'); }
);

function init() {
    $('.menu_title').click(function(){
        $(this).next().eq(0).toggle();
    });
    
    $('.menu_list li a').click(function(){
        $('.menu_list li').removeClass('hover');
        $(this).parent().addClass('hover');
    });

    $('.menu_list li a').attr('target', 'subFrame').click(function(){
        $('#subFrame').attr('src', $(this).attr('href'));
        return false;
    });
}

function setDefaultFrame() {
    $('.menu_list li').removeClass('hover');    
    var node = $('.menu_list li a').eq(0);
    node.parent().addClass('hover');
    $('#subFrame').attr('src', node.attr('href'));
}

function doListChange(obj) {
    $('.menu_list').hide();
    $(this).next().eq(0).show();
}
</script>
</body>
</html>
